package pm.tarea;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        PanelDer = new javax.swing.JPanel();
        TextLogin = new javax.swing.JLabel();
        PanelIzq = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        FieldUsuario = new javax.swing.JTextField();
        LabelContra = new javax.swing.JLabel();
        FieldContra = new javax.swing.JPasswordField();
        BotonIngresar = new javax.swing.JButton();
        LabelContraI = new javax.swing.JLabel();
        Bienvenida = new javax.swing.JLabel();
        Confirmacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(794, 451));
        setMinimumSize(new java.awt.Dimension(793, 450));
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDer.setBackground(new java.awt.Color(255, 255, 204));

        TextLogin.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        TextLogin.setText("Login");

        javax.swing.GroupLayout PanelDerLayout = new javax.swing.GroupLayout(PanelDer);
        PanelDer.setLayout(PanelDerLayout);
        PanelDerLayout.setHorizontalGroup(
            PanelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(TextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelDerLayout.setVerticalGroup(
            PanelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        Fondo.add(PanelDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, 450));

        PanelIzq.setBackground(new java.awt.Color(255, 255, 204));

        Logo.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 0, 0));
        Logo.setText("SensorMax");

        javax.swing.GroupLayout PanelIzqLayout = new javax.swing.GroupLayout(PanelIzq);
        PanelIzq.setLayout(PanelIzqLayout);
        PanelIzqLayout.setHorizontalGroup(
            PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIzqLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelIzqLayout.setVerticalGroup(
            PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzqLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 363, Short.MAX_VALUE))
        );

        Fondo.add(PanelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 450));

        LabelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        LabelUsuario.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LabelUsuario.setText("Usuario");
        Fondo.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 120, 20));

        FieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUsuarioActionPerformed(evt);
            }
        });
        Fondo.add(FieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 190, -1));

        LabelContra.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        LabelContra.setForeground(new java.awt.Color(0, 0, 0));
        LabelContra.setText("Contraseña");
        Fondo.add(LabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 110, 20));
        Fondo.add(FieldContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 190, -1));

        BotonIngresar.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        BotonIngresar.setForeground(new java.awt.Color(0, 0, 0));
        BotonIngresar.setText("INGRESAR");
        BotonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        Fondo.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 100, -1));

        LabelContraI.setBackground(new java.awt.Color(255, 51, 51));
        LabelContraI.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        LabelContraI.setForeground(new java.awt.Color(255, 51, 51));
        Fondo.add(LabelContraI, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 300, -1));

        Bienvenida.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        Bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        Bienvenida.setText("Bienvenido ingrese sus datos para continuar...");
        Fondo.add(Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 280, 50));

        Confirmacion.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        Confirmacion.setForeground(new java.awt.Color(255, 0, 0));
        Fondo.add(Confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 440, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUsuarioActionPerformed

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        //Consultamos los datos a la api
        String username = FieldUsuario.getText();
        String contra = String.valueOf(FieldContra.getPassword());
        ResponseLogin reponse = new ResponseLogin();
        try {
            String respuesta = reponse.POST(username, contra);
            if(!(respuesta == "500")){
                Monitoreo monitoreo = new Monitoreo(respuesta);
                monitoreo.setVisible(true);
                this.setVisible(false);     
            }else{
                this.Confirmacion.setText("Contraseña o usuarios incorrectos, intente nuevamente.");
            }
            
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JLabel Confirmacion;
    private javax.swing.JPasswordField FieldContra;
    private javax.swing.JTextField FieldUsuario;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel LabelContra;
    private javax.swing.JLabel LabelContraI;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelDer;
    private javax.swing.JPanel PanelIzq;
    private javax.swing.JLabel TextLogin;
    // End of variables declaration//GEN-END:variables
}
